# Ansible playbook to demonstrate variable usage and debugging
- name: Print variables
  hosts: localhost
  connection: local
  gather_facts: false # Fact gathering is disabled for performance

  vars:
    # Playbook-level variables
    x: 100
    y: 200

  tasks:
    - name: Display the values of x and y
      ansible.builtin.debug:
        msg: "x = {{ x }}, y = {{ y }}"
